jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB12D0CF2A4648EFA1CBCD9602269CBF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E9A8C97E80CB4745B7D529EFE6BCBE5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9012B03AE9C45F6864D8222D8820FDC }}

      - name: Check slot status
        run: |
          az webapp deployment slot show \
            --name 'webutveklinglabb3-client' \
            --resource-group 'RG-yazanalnsierat' \
            --slot 'Production' || echo "Slot not found, proceeding with deployment"

      - name: Ensure deployment slot is free
        run: |
          az webapp deployment slot delete \
            --name 'webutveklinglabb3-client' \
            --resource-group 'RG-yazanalnsierat' \
            --slot 'Production' --yes || echo "No active deployment in the slot"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webutveklinglabb3-client'
          slot-name: 'Production'
          package: ${{ runner.temp }}/_github_workflow/.net-app
        retry: 3